name: stun_consent
description: Consent Screen for obtaining user permission to collect personal data.
version: 1.0.0
homepage: https://stun-apps.com/
repository: https://github.com/STUN-Apps-Dev/stun_consent
issue_tracker: https://github.com/STUN-Apps-Dev/stun_consent/issues

environment:
  sdk: ">=2.19.2 <4.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  shared_preferences: ^2.3.3
  url_launcher: ^6.3.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - packages/stun_consent/logo.png
